database:
  echo_sql: false
  type: sqlite
  url: sqlite:///market_maker.db
logging:
  file_path: logs/market_maker.log
  format: '{time} | {level} | {module}:{line} | {message}'
  level: INFO
  max_file_size: 10MB
  retention: 30 days
prophet_api:
  base_url: https://api-ss-sandbox.betprophet.co
  tournaments:
  - MLB
  - NBA
  - NFL
  - NHL
risk:
  max_daily_loss: 500.0
  max_drawdown: 0.1
  max_position_size: 100.0
  position_limits: {}
  stop_loss_percentage: 0.05
strategy:
  inventory_target: 0
  max_position: 100
  quote_refresh_seconds: 5
  rebalance_threshold: 10
  spread_margin: 0.02
  strategy_type: simple_market_maker
trading:
  default_stake: 5.0
  dry_run: true
  max_concurrent_wagers: 50
  max_odds: 200
  max_stake_per_wager: 10.0
  max_total_exposure: 1000.0
  min_odds: -200
  wager_frequency_seconds: 30
web:
  auto_reload: false
  enable_dashboard: true
  host: 127.0.0.1
  port: 8000
